---
version: '3'
services:
  syncthing:
    # container_name: syncthing
    image: lscr.io/linuxserver/syncthing:latest
    environment:
      PUID: 1000
      PGID: 1000
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
      # Limit CPU Usage
      GOMAXPROCS: 1
    volumes:
      - ./config:/config
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    # network_mode: host
    dns:
      - 9.9.9.9
      - 1.1.1.1
    healthcheck:
      test: curl --fail -s http://localhost:8384/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    # ports:
    #   - 8384:8384
    #   - 22000:22000/tcp
    #   - 22000:22000/udp
    #   - 21027:21027/udp
    networks:
      - syncthing

networks:
   syncthing: