---
version: "2.4"

volumes:
  data:

networks:
   syncthing:

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    # hostname: syncthing
    networks:
      - syncthing
    # cpu_count: 1
    # cpus: 0.6
    # cpu_percent: 30
    # mem_limit: 500m
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Santiago
      # Limit CPU Usage
      GOMAXPROCS: 1
    volumes:
      - ./config:/config
      - ./data:/data
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    healthcheck:
      test: curl --fail -s http://localhost:8384/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
  # proxy:
  #   image: nginx:stable-alpine
  #   networks:
  #     - syncthing
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 8084:80
  #     - 8443:443
  #   restart: unless-stopped
  #   healthcheck:
  #     test: curl --fail -s http://localhost:80/ || exit 1
  #     interval: 1m30s
  #     timeout: 10s
  #     retries: 3